default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pierredemilly

development:
  <<: *default
  database: schoolabadmin_dev

test:
  <<: *default
  database: schoolapp-admin_test
